export const ROUTES = {
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  changePassword: "/change-password",
  dashboard: "/dashboard",
  livres: "/livres",
  livreDetail: (id: number) => `/livres/${id}`,
  livreNouveau: "/admin/livres/nouveau",
  livreModifier: (id: number) => `/admin/livres/${id}/modifier`,
  emprunts: "/emprunts",
  nouvelEmprunt: "/emprunts/nouveau",
  reservations: "/reservations",
  relances: "/relances",
  rapports: "/rapports",
  utilisateurs: "/utilisateurs",
  utilisateurDetail: (id: number) => `/utilisateurs/${id}`,
  utilisateurNouveau: "/admin/utilisateurs/nouveau",
  acquisitions: "/acquisitions",
  finances: "/finances",
  personnel: "/personnel",
  periodiques: "/periodiques",
  communication: "/communication",
  administration: "/administration",
  fournisseurs: "/fournisseurs",
  profil: "/profil",
  espaceMembre: "/espace-membre",
  presentationEquipe: "/presentation-equipe",
} as const;
